Error
InvestArea Load (1.3ms)  SELECT  "invest_areas".* FROM "invest_areas" WHERE (cadastre_number = '02:74:031501:249')  ORDER BY "invest_areas"."id" ASC LIMIT 1
NameError: uninitialized constant InvestMap::Unicode
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:3230:in `block in check_value_in_type_area_list'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:3229:in `each'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:3229:in `check_value_in_type_area_list'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:3208:in `check_type_in_list'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2535:in `block (2 levels) in processing_invest_data'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:428:in `block in each'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:427:in `upto'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:427:in `each'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2502:in `block in processing_invest_data'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:398:in `block in each_with_pagename'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:397:in `each'
	from /var/lib/gems/2.3.0/gems/roo-1.13.2/lib/roo/base.rb:397:in `each_with_pagename'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2400:in `processing_invest_data'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2299:in `copy_and_read_file'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2234:in `block in read_ftp_files'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2222:in `each'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2222:in `read_ftp_files'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:2199:in `import_from_ftp'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:438:in `import'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/lib/invest_map.rb:323:in `import_with_reload'
	from (irb):10
	from /usr/lib/ruby/vendor_ruby/rails/commands/console.rb:110:in `start'
	from /usr/lib/ruby/vendor_ruby/rails/commands/console.rb:9:in `start'
	from /usr/lib/ruby/vendor_ruby/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/lib/ruby/vendor_ruby/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/lib/ruby/vendor_ruby/rails/commands.rb:17:in `<top (required)>'
	from /home/bulychev_ay/WORK/workflow/sokol_dev/bin/rails:8:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
irb(main):011:0> ^C